CREATE TABLE [enum].[ApiProviderType](
	[Id] [int] NOT NULL,
	[ProviderName] [varchar](50) NULL,
 CONSTRAINT [PK_ApiProviderType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


