CREATE TABLE [enum].[ApiActionType](
	[Id] [int] NOT NULL,
	[ActionName] [varchar](50) NULL,
 CONSTRAINT [PK_ApiActionType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


